In [51]:
import pandas as pd
df=pd.read_csv("carprices.csv")
df.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [7]:
dummy=pd.get_dummies(df["Car Model"])

In [8]:
dummy

Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [12]:
dummy.replace([True,False],[1,0],inplace=True)

C:\Users\Jeddah Pc\AppData\Local\Temp\ipykernel_22156\2585858748.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dummy.replace([True,False],[1,0],inplace=True)


In [13]:
dummy

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [16]:
final=pd.concat([dummy,df],axis=1)

In [17]:
final

Audi A5  BMW X5  Mercedez Benz C class              Car Model  Mileage  \
0         0       1                      0                 BMW X5    69000   
1         0       1                      0                 BMW X5    35000   
2         0       1                      0                 BMW X5    57000   
3         0       1                      0                 BMW X5    22500   
4         0       1                      0                 BMW X5    46000   
5         1       0                      0                Audi A5    59000   
6         1       0                      0                Audi A5    52000   
7         1       0                      0                Audi A5    72000   
8         1       0                      0                Audi A5    91000   
9         0       0                      1  Mercedez Benz C class    67000   
10        0       0                      1  Mercedez Benz C class    83000   
11        0       0                      1  Mercedez Benz C class    79000   
12        0       0                      1  Mercedez Benz C class    59000   

    Sell Price($)  Age(yrs)  
0           18000         6  
1           34000         3  
2           26100         5  
3           40000         2  
4           31500         4  
5           29400         5  
6           32000         5  
7           19300         6  
8           12000         8  
9           22000         6  
10          20000         7  
11          21000         7  
12          33000         5

In [20]:
final.drop(["Audi A5","Car Model"],axis=1,inplace=True)

In [21]:
final

BMW X5  Mercedez Benz C class  Mileage  Sell Price($)  Age(yrs)
0        1                      0    69000          18000         6
1        1                      0    35000          34000         3
2        1                      0    57000          26100         5
3        1                      0    22500          40000         2
4        1                      0    46000          31500         4
5        0                      0    59000          29400         5
6        0                      0    52000          32000         5
7        0                      0    72000          19300         6
8        0                      0    91000          12000         8
9        0                      1    67000          22000         6
10       0                      1    83000          20000         7
11       0                      1    79000          21000         7
12       0                      1    59000          33000         5

In [29]:
x=final.drop(["Sell Price($)"],axis=True)
x

BMW X5  Mercedez Benz C class  Mileage  Age(yrs)
0        1                      0    69000         6
1        1                      0    35000         3
2        1                      0    57000         5
3        1                      0    22500         2
4        1                      0    46000         4
5        0                      0    59000         5
6        0                      0    52000         5
7        0                      0    72000         6
8        0                      0    91000         8
9        0                      1    67000         6
10       0                      1    83000         7
11       0                      1    79000         7
12       0                      1    59000         5

In [26]:
y=final["Sell Price($)"]

In [27]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

In [28]:
reg.fit(x,y)

LinearRegression()

In [30]:
reg.predict([[0,1,45000,4]])

C:\Users\Jeddah Pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36991.31721062])

In [31]:
reg.predict([[1,0,86000,7]])

C:\Users\Jeddah Pc\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11080.74313219])

In [34]:
round(reg.score(x,y)*100,2)

94.17

In [28]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [52]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [53]:
df["Car Model"]=le.fit_transform(df["Car Model"])

In [46]:
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [54]:
x=df[["Car Model"]].values
y=df["Sell Price($)"]
x

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]])

In [55]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [56]:
x=ohe.fit_transform(x).toarray()
x

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [57]:
x=x[:,1:]
x

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [58]:
x1=df[["Mileage","Age(yrs)"]].values

In [59]:
import numpy as np
x=np.hstack((x,x1))
x

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [60]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

In [61]:
reg.fit(x,y)

LinearRegression()

In [62]:
reg.predict([[0,1,45000,4]])

array([36991.31721062])

In [63]:
reg.predict([[1,0,86000,7]])

array([11080.74313219])